#!/usr/bin/env bash
#This is fizzbuzz
i=0
while [ $i -lt 101 ];
do
	if [ $((i % 3)) = 0 ] && [ $((i % 5)) = 0 ];
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) = 0 ];
	then
		echo "Fizz"
	elif [ $((i % 5)) = 0 ];
	then
	    echo "Buzz"
	else
	    echo $i
	fi
	((i++))
done
